### ISSUE TITLE
ModuleNotFoundError: No module named 'progress'

### ISSUE THREAD

**Issue by XcantloadX** [pur1fying/blue_archive_auto_script#12]
运行程序失败，错误信息如下：
```
Collecting progress~=1.3 (from uiautomator2==2.16.23->-r ./requirements.txt (line 3))
  Using cached progress-1.6.tar.gz (7.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\<USERNAME>\AppData\Local\Temp\pip-install-xp7aid2m\progress_68afdc4275c040de912175c12954b3e1\setup.py", line 5, in <module>
          import progress
      ModuleNotFoundError: No module named 'progress'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
2023-10-24 22:47:23,410 - INFO: Install requirements success
2023-10-24 22:47:23,410 - INFO: Checking onnxruntime.InferenceSession Bug solution...
Traceback (most recent call last):
  File "installer.py", line 194, in check_install
  File "installer.py", line 87, in check_onnxruntime
FileNotFoundError: [Errno 2] No such file or directory: './lib/Lib/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py'
请按任意键继续. . .
```

另外新建一个 conda 环境运行，`pip -r requirements.txt` 没有出错，但是运行的时候出错了
```
(baas) PS C:\Users\<USERNAME>\Downloads\blue_archive_auto_script-master> py .\window.py
Traceback (most recent call last):
  File "C:\Users\<USERNAME>\Downloads\blue_archive_auto_script-master\window.py", line 13, in <module>
    from gui.fragments.home import HomeFragment
  File "C:\Users\<USERNAME>\Downloads\blue_archive_auto_script-master\gui\fragments\home.py", line 12, in <module>
    from main import Main
  File "C:\Users\<USERNAME>\Downloads\blue_archive_auto_script-master\main.py", line 11, in <module>
    import module
  File "C:\Users\<USERNAME>\Downloads\blue_archive_auto_script-master\module\__init__.py", line 1, in <module>
    from .total_force_fight import implement
  File "C:\Users\<USERNAME>\Downloads\blue_archive_auto_script-master\module\total_force_fight.py", line 2, in <module>
    from core.utils import get_x_y, kmp
  File "C:\Users\<USERNAME>\Downloads\blue_archive_auto_script-master\core\utils.py", line 1, in <module>
    import cv2
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python310\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python310\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python310\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\<USERNAME>\AppData\Local\Programs\Python\Python310\lib\site-packages\cv2\gapi\__init__.py", line 301, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
(baas) PS C:\Users\<USERNAME>\Downloads\blue_archive_auto_script-master>
```

**Comment by pur1fying** [comment]
可以加qq群试试最新的版本

**Comment by Kiramei** [comment]
最新版release包已经附带编译好的progress
