### ISSUE TITLE
Update Config Organization （Draft）

### ISSUE THREAD

**Issue by pur1fying** [pur1fying/blue_archive_auto_script#208]
https://github.com/pur1fying/blue_archive_auto_script/blob/35bbdc72176b095d8e16532fde223b5286605eac/gui/util/config_set.py#L54-L66
ConfigSet class is widely used in BAAS Gui and Script.

This class need to update with following features:

1.About self.static_config
Expection :  static_config should only be loaded **once** .
Implement :  Make static_config the static member of this class.

2.About self.config which stores config.json (user config)
Expection : 
(1) Gui and Script should share one config. 
(2) If user modifies a config of a task when the Scripting is running. When the task is executed next time( Script not stop ), Script should use the modified config.

3.About event_config which stores event.json (control script scheduling)
Current Implement :

**Comment by MC-ALL** [comment]
Hello Maintainer, this is indeed a meaningful improvement. I have an idea: would it be possible to use the `@dataclass` decorator or directly encapsulate all the data into a single class to make it more convenient to use and better for hint?

**Comment by pur1fying** [comment]
I‘m not so familiar with python decorator. But I will learn about it and consider your suggestion.

**Comment by Kiramei** [comment]
@pur1fying Here's a intro from ChatGPT:

The `@dataclass` decorator in Python is a feature introduced in Python 3.7 (and available in earlier versions through the `dataclasses` module). It simplifies the creation of data-centric classes by automatically generating common methods like `__init__`, `__repr__`, and `__eq__`. Here's a detailed explanation of its functionality:

---

### **Key Features**

1. **Automatic Constructor Generation (`__init__`)**:
   Using `@dataclass`, attributes of a class are automatically added as parameters to the constructor, and the corresponding assignments are handled.

   ```python
   from dataclasses import dataclass

   @dataclass
   class Point:
       x: int
       y: int

   p = Point(1, 2)  # Automatically generated __init__ method
   print(p)         # Output: Point(x=1, y=2)
   ```

2. **Automatic `__repr__` Method**:
   A readable string representation of the class is automatically generated, making it convenient for debugging.

   ```python
   print(Point(3, 4))  # Output: Point(x=3, y=4)
   ```

3. **Automatic Comparison Methods (`__eq__`, etc.)**:
   The decorator generates comparison methods based on the values of the attributes, making it easy to compare instances.

   ```python
   p1 = Point(1, 2)
   p2 = Point(1, 2)
   print(p1 == p2)  # Output: True
   ```

4. **Default Values**:
   You can provide default values for attributes or use `field` for more complex defaults.

   ```python
   from dataclasses import field

   @dataclass
   class Point:
       x: int = 0
       y: int = field(default_factory=lambda: 10)  # Default value of 10

   print(Point())  # Output: Point(x=0, y=10)
   ```

5. **Immutable Classes**:
   By setting `frozen=True`, you can create immutable data classes.

   ```python
   @dataclass(frozen=True)
   class Point:
       x: int
       y: int

   p = Point(1, 2)
   # p.x = 3  # Raises an error because the class is immutable
   ```

---

### **Common Parameters**

- `init`: Whether to generate the `__init__` method (default is `True`).
- `repr`: Whether to generate the `__repr__` method (default is `True`).
- `eq`: Whether to generate the `__eq__` method (default is `True`).
- `order`: Whether to generate comparison methods like `<` and `>` (default is `False`).
- `frozen`: Whether to make the class immutable (default is `False`).
- `kw_only`: Requires keyword-only arguments for initialization (introduced in Python 3.10).

---

### **Use Cases**

1. **Simple Data Objects**: Examples include geometric points, configuration settings, or user information.
2. **Lightweight Data Storage**: Ideal for replacing manually defined `__init__` and `__repr__` methods.
3. **Immutable Data**: Use `frozen=True` for defining immutable objects.

---

### **Summary**

The `@dataclass` decorator is a powerful tool for creating data-centric classes. It significantly reduces boilerplate code, improving code readability and development efficiency, especially in scenarios requiring frequent creation of simple data classes.

**Comment by pur1fying** [comment]
@MC-ALL Hello, I have changed the config class with dateclass decorator （folder core/config）（branch pur1fy_dev）. But I'm not sure if my codes are correct or suitable.If you have spared time, please help me to revierw the code.

**Comment by MC-ALL** [comment]
@pur1fying Thinks for your work to make it possible. I don't think that would cause any problem. By the way, as some code under `window.py` not be changed and use the old getting or setting function, `GUI` is broken now .

e.g.
```shell
Traceback (most recent call last):
  File "/home/circuitx/Work/baas_dev/blue_archive_auto_script/window.py", line 556, in onTabAddRequested
    if text in list(map(lambda x: x.config['name'], self.config_dir_list)):
  File "/home/circuitx/Work/baas_dev/blue_archive_auto_script/window.py", line 556, in <lambda>
    if text in list(map(lambda x: x.config['name'], self.config_dir_list)):
TypeError: 'Config' object is not subscriptable
[1]    107500 IOT instruction (core dumped)  /home/circuitx/Work/baas_dev/blue_archive_auto_script/env/bin/python 
```

**Comment by pur1fying** [comment]
> [@pur1fying](https://github.com/pur1fying) Thinks for your work to make it possible. I don't think that would cause any problem. By the way, as some code under `window.py` not be changed and use the old getting or setting function, `GUI` is broken now .
> 
> e.g.
> 
> Traceback (most recent call last):
>   File "/home/circuitx/Work/baas_dev/blue_archive_auto_script/window.py", line 556, in onTabAddRequested
>     if text in list(map(lambda x: x.config['name'], self.config_dir_list)):
>   File "/home/circuitx/Work/baas_dev/blue_archive_auto_script/window.py", line 556, in <lambda>
>     if text in list(map(lambda x: x.config['name'], self.config_dir_list)):
> TypeError: 'Config' object is not subscriptable
> [1]    107500 IOT instruction (core dumped)  /home/circuitx/Work/baas_dev/blue_archive_auto_script/env/bin/python

fixed

**Comment by MC-ALL** [comment]
@pur1fying Some Task Func under `/module` is still broken by this change. This Feature does needs more test.

e.g. Cafe Invite
```shell
Traceback (most recent call last):
  File "/home/circuitx/Work/baas_dev/blue_archive_auto_script/core/Baas_thread.py", line 469, in solve
    return func_dict[activity](self)
  File "/home/circuitx/Work/baas_dev/blue_archive_auto_script/module/cafe_reward.py", line 21, in implement
    invite_girl(self, 1)
  File "/home/circuitx/Work/baas_dev/blue_archive_auto_script/module/cafe_reward.py", line 346, in invite_girl
    method = self.config['cafe_reward_invite' + str(no) + '_criterion']
TypeError: 'Config' object is not subscriptable
```
e.g. Lesson
```shell
Traceback (most recent call last):
  File "/home/circuitx/Work/baas_dev/blue_archive_auto_script/core/Baas_thread.py", line 469, in solve
    return func_dict[activity](self)
  File "/home/circuitx/Work/baas_dev/blue_archive_auto_script/module/lesson.py", line 34, in implement
    if self.config.get("lesson_enableInviteFavorStudent"):
AttributeError: 'Config' object has no attribute 'get'
```

**Comment by pur1fying** [comment]
fixed
