### ISSUE TITLE
想问一下大佬BAAS点击启动闪退的问题

### ISSUE THREAD

**Issue by HEHEMonster** [pur1fying/blue_archive_auto_script#23]
使用的是mumu12，模拟器尺寸已经改成1280x720了，但是一点击启动就软件闪退

**Comment by pur1fying** [comment]
error.log有无

**Comment by HEHEMonster** [comment]
看了下记事本里是空的...

**Comment by Kiramei** [comment]
error.log里应该有啊，要么就是环境没装对

**Comment by 6FanWQ9** [comment]
我的Bass只能启动ba，每次在To the main page这句话的时候界面就不能点击了，然后就闪退了。这是error.log
```
[W 231116 22:50:55 __init__:218] [pid:2796] atx-agent has something wrong, auto recovering
[I 231116 22:50:55 __init__:357] [pid:2796] [127.0.0.1:7555] device reconnecting, time left(3.0s)
[D 231116 22:50:56 __init__:363] [pid:2796] [127.0.0.1:7555] adb reconnect error: adb read timeout
[I 231116 22:50:57 __init__:357] [pid:2796] [127.0.0.1:7555] device reconnecting, time left(1.0s)
[D 231116 22:50:58 __init__:363] [pid:2796] [127.0.0.1:7555] adb reconnect error: adb read timeout
[W 231116 22:50:59 __init__:218] [pid:2796] atx-agent has something wrong, auto recovering
[I 231116 22:50:59 __init__:357] [pid:2796] [127.0.0.1:7555] device reconnecting, time left(3.0s)
[D 231116 22:51:00 __init__:363] [pid:2796] [127.0.0.1:7555] adb reconnect error: adb read timeout
[I 231116 22:51:01 __init__:357] [pid:2796] [127.0.0.1:7555] device reconnecting, time left(1.0s)
[D 231116 22:51:02 __init__:363] [pid:2796] [127.0.0.1:7555] adb reconnect error: adb read timeout
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "D:\APP\BAAS\main.py", line 655, in simple_error
    raise ScriptError(message=info, context=self)
  File "D:\APP\BAAS\core\exception.py", line 17, in __init__
    self.log_into_file()
  File "D:\APP\BAAS\core\exception.py", line 23, in log_into_file
    screenshot = self.context.connection.screenshot()
  File "D:\APP\BAAS\env\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\APP\BAAS\env\lib\site-packages\retry\api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "D:\APP\BAAS\env\lib\site-packages\retry\api.py", line 33, in __retry_internal
    return f()
  File "D:\APP\BAAS\env\lib\site-packages\uiautomator2\__init__.py", line 938, in screenshot
    r = self.http.get("/screenshot/0", timeout=10)
  File "D:\APP\BAAS\env\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "D:\APP\BAAS\env\lib\site-packages\uiautomator2\__init__.py", line 223, in request
    self.__client._prepare_atx_agent()
  File "D:\APP\BAAS\env\lib\site-packages\uiautomator2\__init__.py", line 316, in _prepare_atx_agent
    raise RuntimeError("USB device %s is offline" % self._serial)
RuntimeError: USB device 127.0.0.1:7555 is offline
[W 231116 22:51:25 __init__:218] [pid:2796] atx-agent has something wrong, auto recovering
[I 231116 22:51:25 __init__:357] [pid:2796] [127.0.0.1:7555] device reconnecting, time left(3.0s)
[D 231116 22:51:25 __init__:317] [pid:2796] [127.0.0.1:7555] device 127.0.0.1:7555 is online
[I 231116 22:51:25 init:156] uiautomator2 version: 2.16.23
[D 231116 22:51:25 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--stop')
[D 231116 22:51:25 init:295] Real version: [0, 10, 0], Expect version: [0, 10, 0]
[D 231116 22:51:25 init:167] Shell: ('/data/local/tmp/atx-agent', 'server', '--nouia', '-d', '--addr', '127.0.0.1:7912')
[I 231116 22:51:25 init:350] Check atx-agent version
[D 231116 22:51:25 init:359] Forward: local:tcp:32762 -> remote:tcp:7912
[D 231116 22:51:25 init:359] Forward: local:tcp:32762 -> remote:tcp:7912
[D 231116 22:51:25 init:362] atx-agent version 0.10.0
[D 231116 22:51:25 init:366] device wlan ip: route ip+net: no such network interface
[D 231116 22:51:28 __init__:661] [pid:2796] [127.0.0.1:7555] kill process(ps): uiautomator
[D 231116 22:51:28 __init__:682] [pid:2796] [127.0.0.1:7555] uiautomator-v2 is starting ... left: 40.0s
[D 231116 22:51:29 __init__:682] [pid:2796] [127.0.0.1:7555] uiautomator-v2 is starting ... left: 39.0s
[D 231116 22:51:30 __init__:682] [pid:2796] [127.0.0.1:7555] uiautomator-v2 is starting ... left: 38.0s
[D 231116 22:51:30 __init__:696] [pid:2796] [127.0.0.1:7555] show float window
[D 231116 22:51:31 __init__:682] [pid:2796] [127.0.0.1:7555] uiautomator-v2 is starting ... left: 36.9s
[I 231116 22:51:31 __init__:643] [pid:2796] [127.0.0.1:7555] uiautomator back to normal
```
