### ISSUE TITLE
[Bug]关于GUI启动时出现的报错问题

### ISSUE THREAD

**Issue by misaka10843** [pur1fying/blue_archive_auto_script#7]
原始问题：https://github.com/pur1fying/blue_archive_auto_script/issues/3#issuecomment-1750801733

关于GUI启动时出现的报错：
```python 
QWidget::setLayout: Attempting to set QLayout "" on HomeFragment "", which already has a layout
QLayout::addChildLayout: layout "" already has a parent
```

然后会导致在显示窗口的一瞬间闪退

~~在短暂的测试发现似乎是因为`gui/fragments/home.py`中的`LoggerBox`问题~~

https://github.com/pur1fying/blue_archive_auto_script/blob/411c7dbfa8237691afa74b6f19fc9a6b1ceccf9f/gui/fragments/home.py#L44-L52

error.log为：
```log
Traceback (most recent call last):
  File "D:\misaka10843\Desktop\blue_archive_auto_script-master\window.py", line 103, in <module>
    w = Window()
  File "D:\misaka10843\Desktop\blue_archive_auto_script-master\window.py", line 45, in __init__
    self.homeInterface = HomeFragment()
  File "D:\misaka10843\Desktop\blue_archive_auto_script-master\gui\fragments\home.py", line 42, in __init__
    self.__initLayout()
  File "D:\misaka10843\Desktop\blue_archive_auto_script-master\gui\fragments\home.py", line 51, in __initLayout
    self._main_thread = Main(logger_box=self.logger)
  File "D:\misaka10843\Desktop\blue_archive_auto_script-master\main.py", line 27, in __init__
    super().__init__()
  File "D:\misaka10843\Desktop\blue_archive_auto_script-master\core\setup.py", line 27, in __init__
    self.ocr = CnOcr(rec_model_name='densenet_lite_114-fc')
  File "D:\misaka10843\Desktop\blue_archive_auto_script-master\venv\lib\site-packages\cnocr\cn_ocr.py", line 155, in __init__
    self.rec_model = rec_cls(
  File "D:\misaka10843\Desktop\blue_archive_auto_script-master\venv\lib\site-packages\cnocr\recognizer.py", line 138, in __init__
    self._model = self._get_model(context)
  File "D:\misaka10843\Desktop\blue_archive_auto_script-master\venv\lib\site-packages\cnocr\recognizer.py", line 191, in _get_model
    model = onnxruntime.InferenceSession(self._model_fp)
  File "D:\misaka10843\Desktop\blue_archive_auto_script-master\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 432, in __init__
    raise e
  File "D:\misaka10843\Desktop\blue_archive_auto_script-master\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\misaka10843\Desktop\blue_archive_auto_script-master\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 451, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['AzureExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['AzureExecutionProvider', 'CPUExecutionProvider'], ...)

```

---

问题二：git问题 https://github.com/pur1fying/blue_archive_auto_script/issues/7#issuecomment-1751541969

**Comment by misaka10843** [comment]
通过报错信息可以查看出似乎是因为在cnocr库未指定providers参数
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/69132853/a2962fae-41c1-4a98-b929-39cc5b563561)

在根据上图修改之后Bug消失
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/69132853/def864a8-8d6d-4402-a23c-c8ba5432afff)

**Comment by Kiramei** [comment]
实际上baas.exe处理了此问题，但这种情况发生原因不明

**Comment by AnRamRan** [comment]
qwq

**Comment by AnRamRan** [comment]
加油

**Comment by misaka10843** [comment]
> 实际上baas.exe处理了此问题，但这种情况发生原因不明

但是启动baas.exe的默认python为3.11，而Polygon3的库在3.9+需要VSMTool的C++编译（正常用户并没有安装这种，所以会报错），所以建议还是将baas的目标py版本改为3.9

然后就是在baas.exe git的时候会提示令牌问题（不知道是网络问题还是什么），
建议直接使用`https://github.com/pur1fying/blue_archive_auto_script.git`
而不是`git@github.com:pur1fying/blue_archive_auto_script.git`
以及提供镜像站的git例如`https://ghproxy.com/https://github.com/pur1fying/blue_archive_auto_script.git`

**Comment by Kiramei** [comment]
最新版release包已经使用virtualenv作为虚拟环境，且已更换镜像源。
