### ISSUE TITLE
[Bug]GUI打开报错

### ISSUE THREAD

**Issue by yxzwym** [pur1fying/blue_archive_auto_script#9]
啥都没动，就在 release 下载了 zip，解压后运行 Baas.exe，等了很久后报错。再打开也是这个报错

```
Collecting progress~=1.3 (from uiautomator2==2.16.23->-r ./requirements.txt (line 3))
  Using cached progress-1.6.tar.gz (7.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-so8aw4f0\progress_80073691cb6245d7a3fd920273865dca\setup.py", line 5, in <module>
          import progress
      ModuleNotFoundError: No module named 'progress'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
2023-10-09 17:53:30,801 - INFO: Install requirements success
2023-10-09 17:53:30,801 - INFO: Checking onnxruntime.InferenceSession Bug solution...
Traceback (most recent call last):
  File "installer.py", line 194, in check_install
  File "installer.py", line 87, in check_onnxruntime
FileNotFoundError: [Errno 2] No such file or directory: './lib/Lib/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py'
请按任意键继续. . .
```

**Comment by pur1fying** [comment]
可以加qq群试试最新的版本

**Comment by Kiramei** [comment]
最新版release包已经附带编译好的progress
